const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'My API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module',
  },

  info: {
    title: 'API Twitter Clone',
    description: 'API do clone do Twitter',
    contact: {
      email: 'seu@email.com.br',
    },
    version: '1.0.0',
  },
  servers: [
    {
      url: 'https://aprickandmorty.herokuapp.com/',
      description: 'API no Heroku',
    },
    {
      url: 'http://localhost:3001',
      description: 'API local',
    },
  ],
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./index.js'];
swaggerAutogen(outputFile, endpointsFiles, doc);

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./index');
});
